/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountWindow: typeof import('./src/components/account/AccountWindow.vue')['default']
    Alert: typeof import('./src/components/Alert.vue')['default']
    IndexNav: typeof import('./src/components/IndexNav.vue')['default']
    LoginCard: typeof import('./src/components/login/LoginCard.vue')['default']
    LoginFormContainer: typeof import('./src/components/login/LoginFormContainer.vue')['default']
    LoginNav: typeof import('./src/components/login/LoginNav.vue')['default']
    LogoShow: typeof import('./src/components/login/LogoShow.vue')['default']
    MemberCard: typeof import('./src/components/MemberCard.vue')['default']
    MemberFram: typeof import('./src/components/MemberFram.vue')['default']
    MemberTitle: typeof import('./src/components/MemberTitle.vue')['default']
    MemberWindow: typeof import('./src/components/MemberWindow.vue')['default']
    MemberWindowbak: typeof import('./src/components/MemberWindowbak.vue')['default']
    PictureCard: typeof import('./src/components/PictureCard.vue')['default']
    PictureRoll: typeof import('./src/components/PictureRoll.vue')['default']
    SignupCard: typeof import('./src/components/signup/SignupCard.vue')['default']
    SignupFormContainer: typeof import('./src/components/signup/SignupFormContainer.vue')['default']
    StudentActivitiesContainer: typeof import('./src/components/student/activities/StudentActivitiesContainer.vue')['default']
    StudentActivitiesShow: typeof import('./src/components/student/activities/StudentActivitiesShow.vue')['default']
    Sylogo: typeof import('./src/components/sylogo.vue')['default']
    TeacherUnscoredContainer: typeof import('./src/components/teacher/unscored/TeacherUnscoredContainer.vue')['default']
    TeacherUnscoredShow: typeof import('./src/components/teacher/unscored/TeacherUnscoredShow.vue')['default']
    UserBar: typeof import('./src/components/public/UserBar.vue')['default']
    UserFormShow: typeof import('./src/components/public/UserFormShow.vue')['default']
  }
}
